In [1]:
import sys
print(sys.executable)

/home/fh/anaconda3/bin/python


In [2]:
import torch
print(torch.__version__)

0.4.0


In [3]:
import numpy as np
import torch.nn as nn

In [4]:
from torchvision import models
models.resnet34?

In [5]:
class MyModule(nn.Module):
    def __init__(self):
        nn.Module.__init__(self)
        self.list = [nn.Linear(3, 4), nn.ReLU()]
        self.module_list = nn.ModuleList([nn.Conv2d(3, 3, 3), nn.ReLU()])
    def forward(self):
        pass
module = MyModule()
module

MyModule(
  (module_list): ModuleList(
    (0): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
    (1): ReLU()
  )
)

In [6]:
a = torch.Tensor([[1, 2], [3, 4], [5, 6]])
a[0, 1] = 100
a = a.float()
print('{}'.format(a))
print('{}'.format(a.size()))

tensor([[   1.,  100.],
        [   3.,    4.],
        [   5.,    6.]])
torch.Size([3, 2])


In [7]:
# Tensor转numpy
numpy_a = a.numpy()
print('{}'.format(numpy_a))
#print('{}'.format(numpy_a.size()))

[[  1. 100.]
 [  3.   4.]
 [  5.   6.]]


In [8]:
# numpy转Tensor
b = numpy.array([[1, 3], [2, 4]])
torch_b = torch.from_numpy(b)
print('{}'.format(torch_b))
print('{}'.format(torch_b.size()))

NameError: name 'numpy' is not defined

In [9]:
#GPU加速
if torch.cuda.is_available():
    a_cuda = a.cuda()
    print(a_cuda)

tensor([[   1.,  100.],
        [   3.,    4.],
        [   5.,    6.]], device='cuda:0')


In [ ]:
#Tensor转Variable
variable_a = torch.autograd.Variable(a)
print('{}'.format(variable_a))

In [ ]:
#反向传播，标量求导
x = torch.autograd.Variable(torch.Tensor([1]), requires_grad=True)
w = torch.autograd.Variable(torch.Tensor([2]), requires_grad=True)
b = torch.autograd.Variable(torch.Tensor([3]), requires_grad=True)
y = w * x + b
y.backward()#自动求导，等价于y.backward(torch.FloatTensor([1]))
print(x.grad)
print(w.grad)
print(b.grad)

In [ ]:
#矩阵求导
x = torch.randn(3)#三维向量
x = Variable(x, requires_grad=True)
y = x * 2
print(y)
y.backward(torch.FloatTensor([1, 0.1, 0.01]))
print(x.grad)

In [ ]:
#数据集处理
import torch
dataiter = DataLoader(myDataset, batch_size=32, shuffle=True, collate_fn=default_collate)
dset = ImageFolder(root='root_path', transform=None, loader=default_loader)